<?php
$LuniAn[0]="Ianuarie";$nzl[0]=31;
$LuniAn[1]="Februarie";$nzl[1]=28;
$LuniAn[2]="Martie";$nzl[2]=31;
$LuniAn[3]="Aprilie";$nzl[3]=30;
$LuniAn[4]="Mai";$nzl[4]=31;
$LuniAn[5]="Iunie";$nzl[5]=30;
$LuniAn[6]="Iulie";$nzl[6]=31;
$LuniAn[7]="August";$nzl[7]=31;
$LuniAn[8]="Septembrie";$nzl[8]=30;
$LuniAn[9]="Octombrie";$nzl[9]=31;
$LuniAn[10]="Noiembrie";$nzl[10]=30;
$LuniAn[11]="Decembrie";$nzl[11]=31;

$LuniAne[1]="January";
$LuniAne[2]="February";
$LuniAne[3]="March";
$LuniAne[4]="April";
$LuniAne[5]="May";
$LuniAne[6]="June";
$LuniAne[7]="July";
$LuniAne[8]="August";
$LuniAne[9]="September";
$LuniAne[10]="October";
$LuniAne[11]="November";
$LuniAne[12]="December";
?>